local L = LibStub("AceLocale-3.0"):NewLocale("EasyExperienceBar", "ptBR", true)

L = L or {}
L["Adds a black outline to text"] = "Adiciona um contorno preto ao texto"
L["Adjust bar size"] = "Ajustar tamanho da barra"
L["Bar Texture"] = "Textura da Barra"
L["Completed & Rested Text"] = "Texto de Concluído e Descansado"
L["Completed Quest XP Bar"] = "Barra de XP de Missões Concluídas"
L["Completed:"] = "Concluído:"
L["Disables the click and drag to move function"] = "Desativa a função de clicar e arrastar para mover"
L["Display"] = "Exibição"
L["Do not hide the bar on max level characters"] = "Não ocultar a barra em personagens de nível máximo"
L["Do not retain stats after a /reload"] = "Não manter estatísticas após um /reload"
L["Easy Experience Bar"] = "Easy Experience Bar"
L["Font"] = "Fonte"
L["Font Selector"] = "Seletor de Fonte"
L["Hide Default Experience Bar"] = "Ocultar Barra de Experiência Padrão"
L["Hides the standard XP bar"] = "Oculta a barra de XP padrão"
L["Information"] = "Informações"
L["Level "] = "Nível"
L["Leveling in:"] = "Subir de nível em:"
L["Leveling Time & XP/Hour Text"] = "Texto de Tempo de Nivelamento e XP/Hora"
L["Lock Bar"] = "Bloquear Barra"
L["Max Level"] = "Nível Máximo"
--[[Translation missing --]]
L["None"] = "None"
--[[Translation missing --]]
L["Outline"] = "Outline"
L["Played Time Text"] = "Texto de Tempo Jogado"
L["Reset Session Time and XP/Hour on Reload UI"] = "Redefinir Tempo da Sessão e XP/Hora ao Recarregar a Interface"
--[[Translation missing --]]
L["Reset Timers"] = "Reset Timers"
--[[Translation missing --]]
L["Resets Session and Level time"] = "Resets Session and Level time"
L["Rested:"] = "Descansado:"
L["Selects the texture used for the bars"] = "Seleciona a textura usada para as barras"
L["Session Time Text"] = "Texto de Tempo da Sessão"
L["Settings"] = "Configurações"
L["Show a bar indicating how much XP is available from completed quests"] = "Mostrar barra indicando quanto XP está disponível de missões concluídas"
L["Show an estimate of how long it takes to hit the next level"] = "Mostrar estimativa de tempo para alcançar o próximo nível"
L["Show Bar at Max Level"] = "Mostrar Barra no Nível Máximo"
L["Show current session time"] = "Mostrar tempo da sessão atual"
L["Show how much rested XP and XP from completed quests the character has"] = "Mostrar quanto XP descansado e XP de missões concluídas o personagem possui"
L["Show Level time text"] = "Mostrar texto de tempo de nível"
L["Size"] = "Tamanho"
L["Text Outline"] = "Contorno do Texto"
--[[Translation missing --]]
L["Thick Outline"] = "Thick Outline"
L["Time played:"] = "Tempo jogado:"
L["Time this level:"] = "Tempo neste nível:"
L["Time this session:"] = "Tempo nesta sessão:"
L["XP/Hour"] = "XP/Hora"
