local L = LibStub("AceLocale-3.0"):NewLocale("EasyExperienceBar", "zhCN", true)

if not L then return end

L["Easy Experience Bar"] = "简易经验条"
L["Information"] = "信息"
L["Played Time Text"] = "游戏时长文本"
L["Show Level time text"] = "显示等级时间文本"
L["Session Time Text"] = "本次时长文本"
L["Show current session time"] = "显示当前会话时间"
L["Leveling Time & XP/Hour Text"] = "升级时间与经验/小时文本"
L["Show an estimate of how long it takes to hit the next level"] = "显示到达下一等级所需的估计时间"
L["Completed & Rested Text"] = "完成与双倍文本"
L["Show how much rested XP and XP from completed quests the character has"] = "显示角色的双倍经验和已完成任务经验"
L["Show Bar at Max Level"] = "满级时显示经验条"
L["Do not hide the bar on max level characters"] = "满级角色不隐藏经验条"
L["Reset Session Time and XP/Hour on Reload UI"] = "重载UI时重置会话时间和经验/小时"
L["Do not retain stats after a /reload"] = "/reload 后不保留统计数据"
L["Hide Default Experience Bar"] = "隐藏默认经验条"
L["Hides the standard XP bar"] = "隐藏标准经验条"
L["Lock Bar"] = "锁定经验条"
L["Disables the click and drag to move function"] = "禁用点击拖动移动功能"
L["Size"] = "大小"
L["Adjust bar size"] = "调整经验条大小"
L["Font"] = "字体"
L["Font Selector"] = "字体选择器"
L["Bar Texture"] = "经验条材质"
L["Selects the texture used for the bars"] = "选择经验条使用的材质"
L["Level "] = "等级"
L["Max Level"] = "满级"
L["Leveling in:"] = "升级剩余:"
L["XP/Hour"] = "经验/小时"
L["Completed:"] = "已完成:"
L["Rested:"] = "双倍:"
L["Time played:"] = "游戏时长:"
L["Time this level:"] = "本级时长:"
L["Time this session:"] = "本次时长:"